server:
  port: 8080     # Springboot占用端口（生产环境）

spring:
  datasource:
    #druid:
      name: ds_mars_base
      driver-class-name: com.mysql.cj.jdbc.Driver
      #driver-class-name: com.mysql.jdbc.Driver
      url : jdbc:mysql://8.129.164.101:3306/mars_base?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username : root
      password : 123456
      # druid 连接池
      type : com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.formice.mars.web.model.entity

logging:
  level:
    root: info

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-shenzhen-internal.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4GDvuSTX1GeExg4MrKWY # 访问身份验证中用到用户标识
    accessKeySecret: vTzze4qZR4I37zYUXvNTVpywoyYqXl # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: bucket-admin # oss的存储空间

spring.servlet.multipart.max-file-size : 500MB
spring.servlet.multipart.max-request-size : 500MB

